-- JAMES KING GAVYN MATHES
-- CPSC 4620 Project Part 2 
-- SQL
-- April 5th 2024
DROP SCHEMA Pizzeria;

DROP TABLE IF EXISTS specifictopping;
DROP TABLE IF EXISTS topping;
DROP TABLE IF EXISTS pizza;
DROP TABLE IF EXISTS base;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS dinein;
DROP TABLE IF EXISTS pickup;
DROP TABLE IF EXISTS ordertable;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS discount;
DROP TABLE IF EXISTS orderdiscount;
DROP TABLE IF EXISTS pizzadiscount;